--1
SET SERVEROUTPUT ON;

CREATE or REPLACE PROCEDURE keskereso(Csz INT)
IS
kesnev VARCHAR(30);
kesara NUMBER(20);
pengehossza DECIMAL(30);
BEGIN
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev INTO  kesnev
FROM KES_BOLT
WHERE KES_BOLT.Cikkszam=csz;
SELECT KES_BOLT.Ar INTO  kesara
FROM KES_BOLT
WHERE KES_BOLT.Cikkszam=csz;
SELECT KES_BOLT.Penge_hossz INTO  pengehossza
FROM KES_BOLT
WHERE KES_BOLT.Cikkszam=csz;
DBMS_OUTPUT.PUT_LINE('Kes: '|| kesnev);
DBMS_OUTPUT.PUT_LINE('Ar: '|| kesara);
DBMS_OUTPUT.PUT_LINE('Penge hossza: '|| pengehossza);
END;

EXECUTE keskereso(1);

--2
CREATE OR REPLACE PROCEDURE mennyirerozsdamentes(csz INT)
IS
kesnev VARCHAR(30);
kesacel VARCHAR(30);
rozsdamentes NUMBER(20);
BEGIN
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev INTO  kesnev
FROM KES_BOLT
WHERE KES_BOLT.Cikkszam=csz;
SELECT  BLADEHQ_ACEL_ERTEKELES.Acel INTO kesacel
FROM BLADEHQ_ACEL_ERTEKELES
INNER JOIN KES_BOLT ON KES_BOLT.ACEL_ID=BLADEHQ_ACEL_ERTEKELES.Id
WHERE KES_BOLT.Cikkszam=csz;
SELECT  BLADEHQ_ACEL_ERTEKELES.Rozsdamentesseg INTO rozsdamentes
FROM BLADEHQ_ACEL_ERTEKELES
INNER JOIN KES_BOLT ON KES_BOLT.ACEL_ID=BLADEHQ_ACEL_ERTEKELES.Id
WHERE KES_BOLT.Cikkszam=csz;
DBMS_OUTPUT.PUT_LINE('Kés: '|| kesnev);
DBMS_OUTPUT.PUT_LINE('Acél: '|| kesacel);
DBMS_OUTPUT.PUT_LINE('Rozsdamentesseg 10/'|| rozsdamentes);
END;

EXECUTE mennyirerozsdamentes(1);

--2
CREATE OR REPLACE PROCEDURE erossegvagas(csz INT)
IS
kesnev VARCHAR(30);
kesacel VARCHAR(30);
eltartasa NUMBER(30);
vagas NUMBER(30);
BEGIN
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev INTO  kesnev
FROM KES_BOLT
WHERE KES_BOLT.Cikkszam=csz;
SELECT  BLADEHQ_ACEL_ERTEKELES.Acel INTO kesacel
FROM BLADEHQ_ACEL_ERTEKELES
INNER JOIN KES_BOLT ON KES_BOLT.ACEL_ID=BLADEHQ_ACEL_ERTEKELES.Id
WHERE KES_BOLT.Cikkszam=csz;
SELECT  BLADEHQ_ACEL_ERTEKELES.Eltartas INTO eltartasa
FROM BLADEHQ_ACEL_ERTEKELES
INNER JOIN KES_BOLT ON KES_BOLT.ACEL_ID=BLADEHQ_ACEL_ERTEKELES.Id
WHERE KES_BOLT.Cikkszam=csz;
SELECT  CEDRIC_CUT_TESTS.Vagasok INTO vagas
FROM CEDRIC_CUT_TESTS
INNER JOIN KES_BOLT ON KES_BOLT.CEDRIC_ID=CEDRIC_CUT_TESTS.Id
WHERE KES_BOLT.Cikkszam=csz;

DBMS_OUTPUT.PUT_LINE('Kés: '|| kesnev);
DBMS_OUTPUT.PUT_LINE('Acél: '|| kesacel);
DBMS_OUTPUT.PUT_LINE('Éltartás 10/'|| eltartasa);
DBMS_OUTPUT.PUT_LINE('Vágások: '|| vagas);

END;

EXECUTE erossegvagas(1);

