--1.
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev MO_Legalis_Kes FROM KES_BOLT
WHERE KES_BOLT.Penge_Hossz <=80;
--2.
SELECT CEDRIC_CUT_TESTS.ACEL,VAGASOK FROM CEDRIC_CUT_TESTS
ORDER BY VAGASOK DESC
FETCH FIRST 1 ROWS ONLY;
--3.
SELECT BLADEHQ_ACEL_ERTEKELES.Acel FROM BLADEHQ_ACEL_ERTEKELES
ORDER BY ACEL;
