--1
SELECT COUNT(Acel) Hatos_Elezes_Dbsz
FROM BLADEHQ_ACEL_ERTEKELES
GROUP BY ELEZES_KONNYEDSEGE
HAVING ELEZES_KONNYEDSEGE = 6;
--2
SELECT GYARTO,COUNT(GYARTO) Kulonbozo_termek_dbsz
FROM KES_BOLT
GROUP BY GYARTO
HAVING COUNT(GYARTO)>1
ORDER BY GYARTO;
--3
SELECT GYARTO,AVG(VAGASOK)
FROM CEDRIC_CUT_TESTS
GROUP BY GYARTO
HAVING AVG(VAGASOK)>85
ORDER BY AVG(VAGASOK) DESC;
