--1
UPDATE KES_BOLT
SET ACEL_ID = 2
WHERE(KES_BOLT.Gyarto='Cold Steel' AND KES_BOLT.Modell_Nev='Broken Skull');
--2
SAVEPOINT Contego_Torles;
DELETE FROM KES_BOLT
WHERE(KES_BOLT.Gyarto='Benchmade' AND KES_BOLT.Modell_Nev='Contego');
--3
INSERT INTO KES_BOLT(Gyarto,Modell_nev,Acel_Id,Penge_Hossz,Penge_Vastagsag,Markolat_Anyag,Zar_Szerkezet,Ar,KESZLET_DARABSZAM,Cedric_Id)
VALUES('Spyderco', 'Native 5', 5, 76,32,'Fluted Carbon Fiber', 'Back-Lock',106290,1,28);
--4
DELETE FROM KES_BOLT
WHERE(Cikkszam=28);
--5
UPDATE (SELECT AR FROM KES_BOLT
WHERE AR = (SELECT MAX(AR) FROM KES_BOLT))
SET AR = AR * 0.8;
--6
SAVEPOINT LEGHOSSZABBKES_TORLES;
DELETE FROM KES_BOLT
WHERE CIKKSZAM=
(SELECT CIKKSZAM
FROM KES_BOLT
WHERE PENGE_HOSSZ =
(SELECT MAX(PENGE_HOSSZ) PENGE_HOSSZ FROM KES_BOLT));
