--1
SELECT CEDRIC_CUT_TESTS.GYARTO,CEDRIC_CUT_TESTS.Modell_Nev,VAGASOK
FROM CEDRIC_CUT_TESTS
WHERE Id IN(
SELECT CEDRIC_Id FROM KES_BOLT
WHERE MODELL_NEV = 'Delica');
--2
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev Kes,BLADEHQ_ACEL_ERTEKELES.ACEL
FROM KES_BOLT,BLADEHQ_ACEL_ERTEKELES
WHERE Acel_Id IN(
SELECT Id
FROM BLADEHQ_ACEL_ERTEKELES
WHERE EROSSEG>5)
ORDER BY Kes;
--3
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev Kes,Keszlet_Darabszam
FROM KES_BOLT
WHERE KES_BOLT.Cikkszam = ANY (SELECT CikkSzam
FROM KES_BOLT
WHERE Keszlet_Darabszam>0);
--4
SELECT KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev Kes,Modell_nev,Ar
FROM KES_BOLT
Where Keszlet_Darabszam>0 AND
Exists (SELECT CikkSzam
FROM KES_BOLT
WHERE Ar<=15000 AND KESZLET_DARABSZAM>0)
ORDER BY AR;
