--1
SELECT  KES_BOLT.Modell_Nev,BLADEHQ_ACEL_ERTEKELES.Acel
FROM BLADEHQ_ACEL_ERTEKELES
INNER JOIN KES_BOLT ON KES_BOLT.ACEL_ID=BLADEHQ_ACEL_ERTEKELES.Id;
--2
SELECT  CEDRIC_CUT_TESTS.Gyarto||' '||CEDRIC_CUT_TESTS.Modell_Nev Kés,KES_BOLT.AR,CEDRIC_CUT_TESTS.VAGASOK
FROM CEDRIC_CUT_TESTS
INNER JOIN KES_BOLT ON KES_BOLT.CEDRIC_ID=CEDRIC_CUT_TESTS.ID;
--3
SELECT  KES_BOLT.Gyarto||' '||KES_BOLT.Modell_Nev Kes,BLADEHQ_ACEL_ERTEKELES.Acel,BLADEHQ_ACEL_ERTEKELES.ROZSDAMENTESSEG
FROM BLADEHQ_ACEL_ERTEKELES
INNER JOIN KES_BOLT ON KES_BOLT.ACEL_ID=BLADEHQ_ACEL_ERTEKELES.Id
ORDER BY BLADEHQ_ACEL_ERTEKELES.ROZSDAMENTESSEG DESC;
